const path = require('path');
const { safeWriteFileSync } = require('./backupManager.cjs');

function renderProgressBar(percentage) {
  const totalBlocks = 10;
  const filledBlocks = Math.max(0, Math.min(10, Math.round(percentage / 10)));
  const emptyBlocks = 10 - filledBlocks;
  const bar = '█'.repeat(filledBlocks) + '░'.repeat(emptyBlocks);
  return `\`[${bar}]\` ${percentage}%`;
}

function formatDate(isoStr) {
  if (!isoStr) return '';
  try {
    const d = new Date(isoStr);
    return d.toISOString().split('T')[0];
  } catch (e) {
    return isoStr;
  }
}

function formatFileSize(bytes) {
  if (!bytes || bytes <= 0) return '0 B';
  const units = ['B', 'KB', 'MB', 'GB'];
  let size = bytes;
  let unitIndex = 0;
  while (size >= 1024 && unitIndex < units.length - 1) {
    size /= 1024;
    unitIndex++;
  }
  return `${size.toFixed(unitIndex === 0 ? 0 : 1)} ${units[unitIndex]}`;
}

function generateMajorGoalsMarkdown(data) {
  const majorTasks = Array.isArray(data.majorTasks) ? data.majorTasks : [];
  const allTasks = Array.isArray(data.tasks) ? data.tasks : [];
  const now = new Date();
  const dateStr = now.toISOString().replace('T', ' ').substring(0, 19);

  let md = '';
  md += `---\n`;
  md += `title: Major Goals & Initiatives\n`;
  md += `last_updated: ${dateStr}\n`;
  md += `total_goals: ${majorTasks.length}\n`;
  md += `completed_goals: ${majorTasks.filter((m) => m.completed).length}\n`;
  md += `active_goals: ${majorTasks.filter((m) => !m.completed).length}\n`;
  md += `---\n\n`;

  md += `# 🎯 Major Goals & Long-Term Initiatives\n\n`;
  md += `> *Auto-generated by Albaqros companion. You can read and reference this document in Obsidian, VS Code, GitHub, or any Markdown reader even without opening Albaqros.*\n\n`;
  md += `**Last Updated:** \`${dateStr}\` | **Total Goals:** \`${majorTasks.length}\`\n\n`;
  md += `---\n\n`;

  if (majorTasks.length === 0) {
    md += `## No Major Goals Created Yet\n\n`;
    md += `You haven't defined any major goals in Albaqros yet. When you create major projects or long-term milestones (e.g., *Game Development*, *Health & Fitness Marathon*, *Product Architecture*), they will automatically be cataloged here with live progress, linked daily tasks, and deliverables.\n\n`;
    return md;
  }

  // Summary Table
  md += `## 📊 Goals Overview\n\n`;
  md += `| Goal | Theme | Target Date | Progress | Status |\n`;
  md += `| :--- | :--- | :--- | :--- | :--- |\n`;

  for (const m of majorTasks) {
    const linked = allTasks.filter((t) => t.majorTaskId === m.id && !t.archived);
    const completedCount = linked.filter((t) => t.completed).length;
    const pct = linked.length > 0 ? Math.round((completedCount / linked.length) * 100) : m.completed ? 100 : 0;
    const statusBadge = m.completed ? '✅ Completed' : m.paused ? '⏸️ Paused' : pct > 0 ? '🟢 In Progress' : '⚪ Planned';
    const target = m.targetDate ? `\`${m.targetDate}\`` : '—';
    const progressStr = linked.length > 0 ? `${renderProgressBar(pct)} (${completedCount}/${linked.length})` : m.completed ? '`[██████████]` 100%' : '`[░░░░░░░░░░]` 0%';

    md += `| [**${m.title}**](#${encodeURIComponent(m.title.toLowerCase().replace(/[^\w\s-]/g, '').trim().replace(/\s+/g, '-'))}) | \`${m.theme || 'General'}\` | ${target} | ${progressStr} | ${statusBadge} |\n`;
  }

  md += `\n---\n\n`;

  // Detailed Section per Major Goal
  for (let i = 0; i < majorTasks.length; i++) {
    const m = majorTasks[i];
    const linked = allTasks.filter((t) => t.majorTaskId === m.id && !t.archived);
    const completedCount = linked.filter((t) => t.completed).length;
    const pct = linked.length > 0 ? Math.round((completedCount / linked.length) * 100) : m.completed ? 100 : 0;
    const statusText = m.completed ? '✅ Completed' : m.paused ? '⏸️ Paused' : pct > 0 ? '🟢 In Progress' : '⚪ Planned';

    md += `## ${i + 1}. ${m.title}\n\n`;
    md += `- **Theme:** \`${m.theme || 'General'}\`\n`;
    if (m.targetDate) md += `- **Target Date:** \`${m.targetDate}\`\n`;
    if (m.cadenceDays) md += `- **Deliverable Cadence:** Every ${m.cadenceDays} days\n`;
    md += `- **Status:** ${statusText}\n`;
    md += `- **Progress:** ${renderProgressBar(pct)} (${completedCount} of ${linked.length} linked tasks completed)\n\n`;

    if (m.description) {
      md += `> ${m.description.split('\n').join('\n> ')}\n\n`;
    }

    // Milestones / Artifacts
    const artifacts = Array.isArray(m.artifacts) ? m.artifacts : [];
    if (artifacts.length > 0) {
      md += `### 🎨 Deliverables & Milestones (${artifacts.length})\n\n`;
      md += `| Milestone | Type | File Name | Size | Date | Notes |\n`;
      md += `| :--- | :--- | :--- | :--- | :--- | :--- |\n`;
      for (const a of artifacts) {
        const typeIcon = a.type === '3d' ? '🧊 3D' : a.type === 'image' ? '🖼️ Image' : a.type === 'audio' ? '🎵 Audio' : '📄 File';
        const date = a.createdAt ? a.createdAt.split('T')[0] : '—';
        const size = formatFileSize(a.fileSize);
        md += `| **${a.title || 'Untitled'}** | ${typeIcon} | \`${a.fileName || '—'}\` | ${size} | ${date} | ${a.notes || '—'} |\n`;
      }
      md += `\n`;
    }

    // Linked Tasks
    md += `### 📌 Linked Tasks & Roadmap (${linked.length})\n\n`;
    if (linked.length === 0) {
      md += `*No daily tasks linked to this goal yet. When you assign tasks with this major goal in Albaqros, they will appear here automatically.*\n\n`;
    } else {
      // Pending tasks first, then completed
      const pendingTasks = linked.filter((t) => !t.completed);
      const doneTasks = linked.filter((t) => t.completed);

      if (pendingTasks.length > 0) {
        md += `#### In-Progress & Next Steps\n\n`;
        for (const t of pendingTasks) {
          const due = t.date ? ` *(Due: ${t.date})*` : '';
          md += `- [ ] **${t.title}**${due}\n`;
          if (t.notes) {
            md += `  > ${t.notes.split('\n').join('\n  > ')}\n`;
          }
          if (Array.isArray(t.subtasks) && t.subtasks.length > 0) {
            for (const st of t.subtasks) {
              md += `  - [${st.completed ? 'x' : ' '}] ${st.title}\n`;
            }
          }
        }
        md += `\n`;
      }

      if (doneTasks.length > 0) {
        md += `#### Completed Tasks (${doneTasks.length})\n\n`;
        for (const t of doneTasks) {
          const finishedDate = t.completedAt ? ` *(Done: ${t.completedAt.split('T')[0]})*` : '';
          md += `- [x] ~~${t.title}~~${finishedDate}\n`;
          if (Array.isArray(t.subtasks) && t.subtasks.length > 0) {
            for (const st of t.subtasks) {
              md += `  - [x] ~~${st.title}~~\n`;
            }
          }
        }
        md += `\n`;
      }
    }

    md += `---\n\n`;
  }

  return md;
}

function generateDailyTasksMarkdown(data) {
  const allTasks = Array.isArray(data.tasks) ? data.tasks : [];
  const majorTasks = Array.isArray(data.majorTasks) ? data.majorTasks : [];
  const majorMap = new Map(majorTasks.map((m) => [m.id, m.title]));

  const now = new Date();
  const todayStr = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`;
  const dateStr = now.toISOString().replace('T', ' ').substring(0, 19);

  const pausedMajorIds = new Set(
    majorTasks.filter((m) => m.paused).map((m) => m.id)
  );
  const activeTasks = allTasks.filter((t) => !t.archived && !t.completed && (!t.majorTaskId || !pausedMajorIds.has(t.majorTaskId)));
  const completedTasks = allTasks.filter((t) => !t.archived && t.completed);

  let md = '';
  md += `---\n`;
  md += `title: Albaqros Daily Tasks & Tracked Actions\n`;
  md += `last_updated: ${dateStr}\n`;
  md += `active_tasks: ${activeTasks.length}\n`;
  md += `completed_tasks: ${completedTasks.length}\n`;
  md += `---\n\n`;

  md += `# 📋 Albaqros Tasks & Action Items\n\n`;
  md += `> *Auto-generated by Albaqros companion. Checklists (- [ ]) and formatting are standard Markdown, ready for Obsidian, VS Code, Logseq, or your preferred note taker.*\n\n`;
  md += `**Date:** \`${todayStr}\` | **Active Tasks:** \`${activeTasks.length}\` | **Completed Archive:** \`${completedTasks.length}\`\n\n`;
  md += `---\n\n`;

  // Top Focus / North Star Tasks
  const topFocusTasks = activeTasks.filter((t) => t.isTopFocus);
  if (topFocusTasks.length > 0) {
    md += `## ⭐ North Star / Top Focus Today\n\n`;
    for (const t of topFocusTasks) {
      renderTaskItem(t);
    }
    md += `\n`;
  }

  // Active Tasks Grouped by Theme
  const themes = Array.from(new Set(activeTasks.map((t) => t.theme || 'General')));
  if (themes.length > 0) {
    md += `## 🚀 Active Tasks by Theme\n\n`;
    for (const theme of themes) {
      const themeTasks = activeTasks.filter((t) => (t.theme || 'General') === theme && !t.isTopFocus);
      if (themeTasks.length === 0) continue;

      md += `### 📂 ${theme} (${themeTasks.length})\n\n`;
      for (const t of themeTasks) {
        renderTaskItem(t);
      }
      md += `\n`;
    }
  } else if (topFocusTasks.length === 0) {
    md += `## 🚀 Active Tasks\n\n`;
    md += `*No active tasks for today. You're all caught up!*\n\n`;
  }

  // Multi-day and Carried Over Tasks
  const multiDayOrMissed = activeTasks.filter((t) => t.isMultiDay || (t.daysMissed && t.daysMissed > 0));
  if (multiDayOrMissed.length > 0) {
    md += `## ⏳ Multi-Day & Carried-Over Focus\n\n`;
    for (const t of multiDayOrMissed) {
      const tag = t.isMultiDay ? '🔄 Multi-Day' : `⚠️ Carried over (${t.daysMissed}d)`;
      md += `- [ ] **${t.title}** \`[${tag}]\` *(Theme: ${t.theme || 'General'})*\n`;
      if (Array.isArray(t.subtasks) && t.subtasks.length > 0) {
        for (const st of t.subtasks) {
          md += `  - [${st.completed ? 'x' : ' '}] ${st.title}\n`;
        }
      }
    }
    md += `\n`;
  }

  // Recurring Routine Tasks
  const recurringTasks = allTasks.filter((t) => t.recurrence && t.recurrence.isRecurring);
  if (recurringTasks.length > 0) {
    md += `## 🔁 Recurring Routines & Habits\n\n`;
    for (const t of recurringTasks) {
      const rule = t.recurrence;
      let freq = rule.type;
      if (rule.type === 'weekly_days' && rule.daysOfWeek) {
        const days = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
        freq = `Weekly (${rule.daysOfWeek.map((d) => days[d]).join(', ')})`;
      } else if (rule.type === 'interval_days') {
        freq = `Every ${rule.intervalDays} days`;
      }
      md += `- [${t.completed ? 'x' : ' '}] **${t.title}** \`[${freq}]\` *(Theme: ${t.theme})*\n`;
    }
    md += `\n`;
  }

  // Completed Tasks Archive
  if (completedTasks.length > 0) {
    md += `## ✅ Completed Tasks Archive (${completedTasks.length})\n\n`;

    // Group completed tasks by completion date or task date
    const completedByDate = {};
    for (const t of completedTasks) {
      const d = t.completedAt ? t.completedAt.split('T')[0] : t.date || 'Earlier';
      if (!completedByDate[d]) completedByDate[d] = [];
      completedByDate[d].push(t);
    }

    const sortedDates = Object.keys(completedByDate).sort().reverse();
    for (const d of sortedDates.slice(0, 15)) {
      md += `### ${d}\n\n`;
      for (const t of completedByDate[d]) {
        const majorName = t.majorTaskId ? majorMap.get(t.majorTaskId) : null;
        const majorTag = majorName ? ` *(Goal: ${majorName})*` : '';
        md += `- [x] ~~${t.title}~~ \`[${t.theme || 'General'}]\`${majorTag}\n`;
        if (Array.isArray(t.subtasks) && t.subtasks.length > 0) {
          for (const st of t.subtasks) {
            md += `  - [x] ~~${st.title}~~\n`;
          }
        }
      }
      md += `\n`;
    }
  }

  function renderTaskItem(t) {
    const majorName = t.majorTaskId ? majorMap.get(t.majorTaskId) : null;
    const majorStr = majorName ? `↳ *Goal:* **${majorName}**` : '';
    const dueStr = t.date && t.date !== todayStr ? `*(Scheduled: ${t.date})*` : '';

    md += `- [ ] **${t.title}** ${dueStr}\n`.replace('  \n', '\n');
    if (majorStr) {
      md += `  ${majorStr}\n`;
    }
    if (t.notes) {
      md += `  > ${t.notes.split('\n').join('\n  > ')}\n`;
    }
    if (Array.isArray(t.subtasks) && t.subtasks.length > 0) {
      for (const st of t.subtasks) {
        md += `  - [${st.completed ? 'x' : ' '}] ${st.title}\n`;
      }
    }
  }

  return md;
}

function syncMarkdownFiles(vaultDir, data) {
  if (!vaultDir || !data) return { success: false, error: 'Missing vaultDir or data' };

  try {
    const goalsMd = generateMajorGoalsMarkdown(data);
    const tasksMd = generateDailyTasksMarkdown(data);

    // Primary human-readable files in vault root
    const majorGoalsPath = path.join(vaultDir, 'Major Goals.md');
    const dailyTasksPath = path.join(vaultDir, 'Daily Tasks.md');

    // Also mirror to goals.md and tasks.md for standard aliases
    const goalsAliasPath = path.join(vaultDir, 'goals.md');
    const tasksAliasPath = path.join(vaultDir, 'tasks.md');

    safeWriteFileSync(majorGoalsPath, goalsMd);
    safeWriteFileSync(dailyTasksPath, tasksMd);
    safeWriteFileSync(goalsAliasPath, goalsMd);
    safeWriteFileSync(tasksAliasPath, tasksMd);

    return {
      success: true,
      majorGoalsPath,
      dailyTasksPath,
      goalsAliasPath,
      tasksAliasPath,
    };
  } catch (err) {
    console.error('[MarkdownSync] Failed to sync markdown files:', err);
    return { success: false, error: err.message };
  }
}

module.exports = {
  generateMajorGoalsMarkdown,
  generateDailyTasksMarkdown,
  syncMarkdownFiles,
};
