export type EnergyLevel = 'high' | 'low' | 'normal';

export type RecurrenceType =
  | 'daily'
  | 'weekdays'
  | 'weekends'
  | 'weekly_days'
  | 'interval_days'
  | 'cycle'
  | 'times_per_week'
  | 'monthly';

export interface RecurrenceRule {
  isRecurring: boolean;
  type: RecurrenceType;
  daysOfWeek?: number[]; // 0 = Sunday, 1 = Monday, ..., 6 = Saturday
  intervalDays?: number; // e.g. every 3 days, every 14 days
  timesPerWeek?: number; // e.g. 3 times a week
  activeDays?: number; // For cycle: e.g. active for 3 days
  skipDays?: number; // For cycle: e.g. skip/rest for 1 day
  cycleStartDate?: string; // YYYY-MM-DD cycle anchor date
  monthlyDay?: number; // 1 to 31
  lastGeneratedDate?: string; // YYYY-MM-DD
}

export interface Subtask {
  id: string;
  title: string;
  completed: boolean;
}

export interface Task {
  id: string;
  title: string;
  theme: string; // e.g., 'Work', 'Health', 'Chores', 'Personal'
  energy?: EnergyLevel; // Optional legacy field
  isTopFocus: boolean; // Pinned #1 North Star focus
  completed: boolean;
  completedAt?: string; // ISO string
  date: string; // YYYY-MM-DD
  createdAt: string; // ISO string
  daysMissed: number; // Count of past days this task was postponed or missed
  recurrence?: RecurrenceRule;
  recurringTemplateId?: string;
  subtasks?: Subtask[];
  majorTaskId?: string; // ID of linked Major Task / Project
  notes?: string;
  archived?: boolean;
  isMultiDay?: boolean; // Spans multiple days; completed subtasks carry over to next day
}

export type ProjectArtifactType = 'image' | 'audio' | '3d' | 'file';

export interface ProjectArtifact {
  id: string;
  majorTaskId: string;
  title: string;
  type: ProjectArtifactType;
  filePath?: string; // Absolute path on disk
  fileName?: string;
  fileSize?: number; // Size in bytes
  fileExtension?: string; // e.g. .png, .blend, .wav
  dataUrl?: string; // Base64 data URL for instant image/audio preview in UI
  thumbnailUrl?: string; // Optional cover / render image
  notes?: string; // Creative reflection, critique, techniques practiced
  createdAt: string; // ISO date string
  milestoneNumber?: number; // e.g. 1 for Piece #1, 2 for Piece #2
  autoGeneratedCover?: boolean; // True if cover was automatically extracted from Krita/Photoshop/Blender
  coverSource?: string; // 'krita' | 'photoshop' | 'blender' | 'shell'
}

export interface MajorTask {
  id: string;
  title: string;
  description?: string;
  theme: string;
  completed: boolean;
  completedAt?: string;
  paused?: boolean; // When paused, linked tasks stop appearing in dailies
  createdAt: string;
  targetDate?: string; // Optional target completion date YYYY-MM-DD
  color?: string;
  cadenceDays?: number; // Target deliverable cadence in days (e.g. every 7 days)
  artifacts?: ProjectArtifact[]; // Creative deliverables / milestones
}

export type DailyPropertyType = 'number' | 'text' | 'boolean';

export interface DailySubpropertyDefinition {
  id: string; // e.g. "subprop-stocks", "subprop-etf"
  name: string; // e.g. "Stocks", "ETF"
  unit?: string; // inherits from parent if not specified
  defaultValue?: number;
}

export interface DailyPropertyDefinition {
  id: string; // e.g. "prop-weight", "prop-investments"
  name: string; // e.g. "Weight", "Investments"
  unit?: string; // e.g. "kg", "$", "hrs", "L"
  type: DailyPropertyType;
  icon?: string;
  defaultValue?: number | string | boolean;
  subproperties?: DailySubpropertyDefinition[]; // Optional breakdown into sub-metrics whose values sum to the parent
}

export type ReminderCategory = 'medication' | 'routine' | 'habit' | 'general';

export interface DailyReminder {
  id: string;
  title: string; // e.g. "Vitamin D", "Saturday Meds"
  category: ReminderCategory;
  dosage?: string; // e.g. "1 capsule with breakfast", "5g"
  recurrence: RecurrenceRule; // daily, weekly_days (e.g. Sat), interval, cycle
  color?: string;
  notes?: string;
  createdAt: string;
}

export interface DayEntry {
  date: string; // YYYY-MM-DD
  journal: string; // Free-style journal entry
  energyLevel?: number; // 1 to 5 daily energy/mood rating
  updatedAt: string;
  properties?: Record<string, number | string | boolean>; // Keyed by property id e.g. { "prop-weight": 78.2 }
  subpropertyValues?: Record<string, Record<string, number>>; // Keyed by [propertyId][subpropertyId] e.g. { "prop-investments": { "subprop-stocks": 12000, "subprop-etf": 5000 } }
  remindersCompleted?: Record<string, boolean>; // Keyed by reminder id e.g. { "rem-1": true }
}

export type CloudProvider = 'onedrive' | 'google-drive' | 'dropbox' | 'icloud' | 'local';

export interface RecentVault {
  path: string;
  name: string;
  lastUsed: string;
}

export interface VaultInfo {
  path: string;
  name: string;
  exists: boolean;
  hasDataFile: boolean;
  dataFilePath: string;
  cloudProvider: CloudProvider;
  isCustom: boolean;
  recentVaults?: RecentVault[];
}

export interface BackupSnapshot {
  id: string;
  fileName: string;
  filePath: string;
  source: 'vault' | 'emergency';
  timestamp: string;
  sizeBytes: number;
  taskCount: number;
  majorTaskCount: number;
  entryCount: number;
  version: number;
}

export interface SelectVaultResult {
  success: boolean;
  vaultInfo?: VaultInfo;
  data?: AppData | null;
  isEmpty?: boolean;
  hasExistingFiles?: boolean;
  error?: string;
}

export interface AppSettings {
  storagePath: string; // Custom Google Drive / OneDrive folder or default
  activeVault?: string; // Active Vault folder path
  runOnStartup: boolean;
  alwaysOnTop: boolean;
  compactMode: boolean;
  defaultEnergyFilter?: 'all' | 'high' | 'low';
}

export interface AppData {
  version: number;
  tasks: Task[];
  entries: Record<string, DayEntry>; // Keyed by YYYY-MM-DD
  recurringTemplates: Task[];
  majorTasks: MajorTask[]; // Major initiatives / long-term projects
  customThemes: string[]; // Dynamically user-defined themes/facets
  dailyProperties?: DailyPropertyDefinition[]; // Tracked metrics like Weight, Investments
  dailyReminders?: DailyReminder[]; // Recurring routine meds and non-task reminders
  settings: AppSettings;
  lastOpenedDate: string; // YYYY-MM-DD
}

export type UpdateState =
  | 'idle'
  | 'checking'
  | 'available'
  | 'not-available'
  | 'downloading'
  | 'downloaded'
  | 'error';

export interface UpdateInfo {
  state: UpdateState;
  version?: string;
  progress?: number;
  bytesPerSecond?: number;
  transferred?: number;
  total?: number;
  error?: string;
  releaseDate?: string;
  releaseNotes?: string;
}

export interface NoteMetadata {
  id: string; // unique relative path or slug, e.g. "learning/shader-basics.md"
  title: string; // Title extracted from # Heading or filename
  fileName: string; // e.g. "shader-basics.md"
  relativePath: string; // relative to vault notes/ directory, e.g. "learning/shader-basics.md"
  folder: string; // e.g. "learning" or "" for root
  tags: string[]; // extracted from content (#tag) or frontmatter
  preview: string; // short text preview for list view
  createdAt: string; // ISO date string
  updatedAt: string; // ISO date string
  size?: number; // File size in bytes
  linkedTasks?: string[]; // IDs of linked tasks
  linkedMajorTasks?: string[]; // IDs of linked major projects
}

export interface Note extends NoteMetadata {
  content: string; // Raw markdown text
}

// ==========================================
// Canvas Studio Types (Obsidian Canvas format)
// ==========================================

export type CanvasNodeType = 'text' | 'image' | 'note' | 'group';

export type CanvasColor =
  | 'default'
  | 'red'
  | 'orange'
  | 'yellow'
  | 'green'
  | 'blue'
  | 'purple';

export interface CanvasNode {
  id: string;
  type: CanvasNodeType;
  x: number;
  y: number;
  width: number;
  height: number;
  color?: CanvasColor | string;
  // For text node:
  text?: string;
  // For image node:
  src?: string; // base64, file:// or url
  alt?: string;
  aspectRatio?: number;
  fitMode?: 'contain' | 'cover';
  // For note node:
  notePath?: string; // relativePath to markdown note
  noteTitle?: string;
  notePreview?: string;
  // For group node:
  label?: string;
  zIndex?: number;
  // Group membership:
  groupId?: string; // ID of the parent group node this node belongs to
}

export type CanvasEdgeSide = 'top' | 'right' | 'bottom' | 'left';

export interface CanvasEdge {
  id: string;
  fromNode: string;
  fromSide: CanvasEdgeSide;
  toNode: string;
  toSide: CanvasEdgeSide;
  label?: string;
  color?: CanvasColor | string;
}

export interface CanvasViewport {
  x: number;
  y: number;
  zoom: number; // 0.1 to 3.0 (1 = 100%)
}

export interface CanvasData {
  nodes: CanvasNode[];
  edges: CanvasEdge[];
  viewport?: CanvasViewport;
}

export interface CanvasMetadata {
  id: string; // relative path, e.g. "GameDesign/character-map.canvas"
  title: string; // e.g. "character-map"
  fileName: string; // e.g. "character-map.canvas"
  relativePath: string; // e.g. "GameDesign/character-map.canvas"
  folder: string; // e.g. "GameDesign" or ""
  createdAt: string;
  updatedAt: string;
  nodeCount?: number;
}

export interface CanvasDocument extends CanvasMetadata {
  data: CanvasData;
}

// ==========================================
// 3D Blender Asset Library Types
// ==========================================

export interface BlenderAssetDimensions {
  x: number;
  y: number;
  z: number;
}

export interface BlenderAssetMetadata {
  vertexCount?: number;
  faceCount?: number;
  objectCount?: number;
  materialCount?: number;
  materials?: string[];
  dimensions?: BlenderAssetDimensions;
}

export interface BlenderAsset {
  id: string; // unique ID or relative path e.g. "asset-1729000000000" or filename
  name: string;
  fileName: string;
  filePath: string; // Absolute path to the .blend file on disk
  relativePath?: string; // Relative to vault models/
  folder?: string; // Subfolder path relative to models/ e.g. "Vehicles" or "" for root
  previewUrl?: string; // Base64 data URL for instant rendering in UI
  previewPath?: string; // Absolute path to rendered preview PNG
  fileSize: number; // Size in bytes
  createdAt: string; // ISO date string
  updatedAt: string; // ISO date string
  category: string; // e.g. "Characters", "Props", "Environment", "Vehicles", "Architecture", "Weapons"
  tags: string[]; // e.g. ["#lowpoly", "#cyberpunk", "#rigged"]
  notes?: string; // Reflection notes, poly budgets, scene notes
  metadata?: BlenderAssetMetadata;
}

// ==========================================
// 2D Creative Art & Asset Library Types
// ==========================================

export type Art2DSoftware = 'krita' | 'photoshop' | 'clipstudio' | 'image' | 'vector' | 'other';

export interface Art2DAssetMetadata {
  width?: number; // Canvas width in px
  height?: number; // Canvas height in px
  aspectRatio?: number; // width / height
  resolutionLabel?: string; // e.g. "4K UHD", "1080p", "Square", "Custom"
  format?: string; // 'kra', 'psd', 'png', 'jpg', 'webp', 'svg', etc.
  colorMode?: string; // 'RGB', 'CMYK', 'Grayscale', 'RGBA'
  bitDepth?: number; // 8, 16, 32
  channels?: number;
  software?: Art2DSoftware;
  layerCount?: number;
  dpi?: number;
  hasAlpha?: boolean;
}

export interface Art2DAsset {
  id: string; // unique ID e.g. "art-1729000000000-xyz"
  name: string; // Clean display name (editable)
  fileName: string; // File name on disk e.g. "cyberpunk_cityscape.kra"
  filePath: string; // Absolute path to file on disk
  relativePath?: string; // Relative to vault art/
  folder?: string; // Subfolder path relative to art/ e.g. "Characters" or "" for root
  previewUrl?: string; // Base64 data URL for instant rendering in UI
  previewPath?: string; // Absolute path to rendered preview PNG in .previews
  fileSize: number; // Size in bytes
  createdAt: string; // ISO date string
  updatedAt: string; // ISO date string
  category: string; // e.g. "Illustrations", "Character Design", "Concept Art", "Environments", "Sketches & Studies", "Sprites & Pixel Art", "UI & Graphic Design", "Textures & Patterns", "WIP / In Progress", "Other"
  tags: string[]; // e.g. ["#digitalart", "#krita", "#portrait", "#wip"]
  notes?: string; // Artist reflection, brush notes, reference links, technique notes
  metadata?: Art2DAssetMetadata;
  software?: Art2DSoftware;
}


